config/routes.rb
Rails.application.routes.draw do

  scope "v3" do
    resources :content_modules, path: "modules" do
      member do
        get "documents"
        get "documents/:document_id" => "content_modules#documents"
      end
    end
    
    get "tokens" => "content_modules#tokens"
    get "users/:user_id" => "content_modules#index" , :defaults => { :format => 'json' }
    get "users/:user_id/modules" => "content_modules#index" , :defaults => { :format => 'json' }
  end

  root 'content_modules#index'

end

app/models/content_module.rb
class ContentModule < ActiveRecord::Base
  extend FriendlyId
  
  friendly_id :meta_title, use: [:slugged, :finders]
  validates :meta_title, length: {maximum: 255}
  validates :meta_attribution, length: {maximum: 255}
  validates :meta_keywords, length: {maximum: 255}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/content_modules_controller.rb
class ContentModulesController < ApplicationController
  before_action :set_content_module, only: [:show, :edit, :update, :destroy]

  # GET /content_modules
  # GET /content_modules.json
  def index
    @content_modules = ContentModule.all
  end

  # GET /content_modules/1
  # GET /content_modules/1.json
  def show
  end

  # GET /content_modules/new
  def new
    @content_module = ContentModule.new
  end

  # GET /content_modules/1/edit
  def edit
  end

  # POST /content_modules
  # POST /content_modules.json
  def create
    @content_module = ContentModule.new(content_module_params)

    respond_to do |format|
      if @content_module.save
        format.html { redirect_to @content_module, notice: 'Content module was successfully created.' }
        format.json { render :show, status: :created, location: @content_module }
      else
        format.html { render :new }
        format.json { render json: @content_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_modules/1
  # PATCH/PUT /content_modules/1.json
  def update
    respond_to do |format|
      if @content_module.update(content_module_params)
        format.html { redirect_to @content_module, notice: 'Content module was successfully updated.' }
        format.json { render :show, status: :ok, location: @content_module }
      else
        format.html { render :edit }
        format.json { render json: @content_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_modules/1
  # DELETE /content_modules/1.json
  def destroy
    @content_module.destroy
    respond_to do |format|
      format.html { redirect_to content_modules_url, notice: 'Content module was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_module
      @content_module = ContentModule.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_module_params
      params.require(:content_module).permit(:meta_attribution, :meta_keywords, :meta_title, :content, :references)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_modules_helper.rb
module ContentModulesHelper
end

app/views/content_modules/_form.html.erb
<%= form_for(@content_module) do |f| %>
  <% if @content_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content_module.errors.count, "error") %> prohibited this content_module from being saved:</h2>

      <ul>
      <% @content_module.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meta_attribution %><br>
    <%= f.text_field :meta_attribution %>
  </div>
  <div class="field">
    <%= f.label :meta_keywords %><br>
    <%= f.text_field :meta_keywords %>
  </div>
  <div class="field">
    <%= f.label :meta_title %><br>
    <%= f.text_field :meta_title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :references %><br>
    <%= f.text_area :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/content_modules/edit.html.erb
<h1>Editing Content Module</h1>

<%= render 'form' %>

<%= link_to 'Show', @content_module %> |
<%= link_to 'Back', content_modules_path %>

app/views/content_modules/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Chapters</h3>
<ul class="nav nav-list">
	<% ContentModule.select("id,meta_title,slug").each do |content_module| %>
 		<li><%= link_to content_module.meta_title, content_module %></li>
	<% end %>
	<li><%= link_to 'New Chapter', new_content_module_path %></li>
</ul>

app/views/content_modules/new.html.erb
<h1>New Content Module</h1>

<%= render 'form' %>

<%= link_to 'Back', content_modules_path %>

app/views/content_modules/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @content_module.meta_title %></h1>

<div class="row">
  <div class="col-md-9">
	<div><%= (@content_module.content || "").html_safe %></div>
	<p>
	  <strong>Attribution:</strong>
	  <%= @content_module.meta_attribution %>
	</p>

	<p>
	  <strong>Keywords:</strong>
	  <%= @content_module.meta_keywords %>
	</p>


	<p>
	  <strong>References:</strong>
	  <%= @content_module.references %>
	</p>

  </div><!-- col-md-9 -->
  <div class="col-md-3">
    <div class="well sidebar-nav">
      <h3>Chapters</h3>
      <ul class="nav nav-list">
			<% ContentModule.select("id,meta_title,slug").each do |content_module| %>
        		<li><%= link_to content_module.meta_title, content_module %></li>
			<% end %>
      </ul>
    </div><!--/.well -->
  </div><!--/span-->
</div><!--/row-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Handbook" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Handbook</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>